version: '3.3'
services:

  haproxy:
    image: haproxy:alpine
    configs: 
      - haproxy_cfg
    networks:
      - app
      - dbs
    deploy:
      placement:
        constraints:
          - node.labels.type == db
    command: haproxy -f /haproxy_cfg
  
  etcd:
    image: quay.io/coreos/etcd:v3.1.2
    configs:
      - etcd_cfg
    volumes:
      - etcd_data:/etcd_data
    networks: 
      - dbs
    deploy:
      placement:
        constraints:
          - node.labels.type == db
    command: /bin/sh /etcd_cfg

  dbnode1:
    image: seocahill/patroni:1.2.5
    volumes:
        - db-1-data:/data
    secrets: 
      - patroni.yml
      - source: aws_access_key_id
        target: /etc/wal-e.d/env/AWS_ACCESS_KEY_ID
      - source: aws_region
        target: /etc/wal-e.d/env/AWS_REGION
      - source: aws_secret_access_key
        target: /etc/wal-e.d/env/AWS_SECRET_ACCESS_KEY
      - source: wale_s3_prefix
        target: /etc/wal-e.d/env/WALE_S3_PREFIX
    configs:
      - source: notification.py
        target: /home/postgres/notification.py
      - source: notification.sh
        target: /home/postgres/notification.sh
    env_file:
      - db-1.env
    networks:
      - dbs
    deploy:
      placement:
        constraints:
          - node.labels.name == db-1
    entrypoint: patroni
    command: /run/secrets/patroni.yml

  dbnode2:
    image: seocahill/patroni:1.2.5
    volumes:
      - db-2-data:/data
    secrets: 
      - patroni.yml
      - source: aws_access_key_id
        target: /etc/wal-e.d/env/AWS_ACCESS_KEY_ID
      - source: aws_region
        target: /etc/wal-e.d/env/AWS_REGION
      - source: aws_secret_access_key
        target: /etc/wal-e.d/env/AWS_SECRET_ACCESS_KEY
      - source: wale_s3_prefix
        target: /etc/wal-e.d/env/WALE_S3_PREFIX
    configs:
      - source: notification.py
        target: /home/postgres/notification.py
      - source: notification.sh
        target: /home/postgres/notification.sh
    env_file:
      - db-2.env
    networks:
      - dbs
    deploy:
      placement:
        constraints:
          - node.labels.name == db-2
    entrypoint: patroni
    command: /run/secrets/patroni.yml
    
  dbnode3:
    image: seocahill/patroni:1.2.5
    volumes:
      - db-3-data:/data
    secrets: 
      - patroni.yml
      - source: aws_access_key_id
        target: /etc/wal-e.d/env/AWS_ACCESS_KEY_ID
      - source: aws_region
        target: /etc/wal-e.d/env/AWS_REGION
      - source: aws_secret_access_key
        target: /etc/wal-e.d/env/AWS_SECRET_ACCESS_KEY
      - source: wale_s3_prefix
        target: /etc/wal-e.d/env/WALE_S3_PREFIX
    configs:
      - source: notification.py
        target: /home/postgres/notification.py
      - source: notification.sh
        target: /home/postgres/notification.sh
    env_file:
      - db-3.env
    networks:
      - dbs
    deploy:
      placement:
        constraints:
          - node.labels.name == db-3
    entrypoint: patroni
    command: /run/secrets/patroni.yml
    
  cron:
    image: seocahill/patroni:1.2.5
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker 
    networks:
      - dbs
    env_file:
      - cron.env
    deploy:
      mode: global
    secrets: 
      - source: aws_access_key_id
        target: /etc/wal-e.d/env/AWS_ACCESS_KEY_ID
      - source: aws_region
        target: /etc/wal-e.d/env/AWS_REGION
      - source: aws_secret_access_key
        target: /etc/wal-e.d/env/AWS_SECRET_ACCESS_KEY
      - source: wale_s3_prefix
        target: /etc/wal-e.d/env/WALE_S3_PREFIX
      - source: aws_default_region
        target: /etc/wal-e.d/env/AWS_DEFAULT_REGION
    configs:
      - crontab
      - source: cron_archive
        target: /etc/cron.daily
      - source: cron_restore_archive
        target: /etc/cron.weekly
      - source: cron_dump
        target: /etc/cron.daily
      - source: cron_restore_dump
        target: /etc/cron.weekly
    entrypoint: bash
    command: cron -f

volumes:
  db-1-data:
  db-2-data:
  db-3-data:
  etcd_data:

networks:
  dbs:
  app:

configs:
  haproxy_cfg:
    file: config/haproxy.cfg
  patroni.yml:
    file: patroni.yml
  cron_archive:
    file: cron/archive.sh
  cron_restore_archive:
    file: cron/restore_archive.sh
  cron_dump:
    file: cron/dump.sh
  cron_restore_dump:
    file: cron/restore_dump.sh
  notification.py:
    file: callbacks/notification.py
  notification.sh:
    file: callbacks/notification.sh

secrets:
  aws_access_key_id:
    file: wal-e/AWS_ACCESS_KEY_ID
  aws_region:
    file: wal-e/AWS_REGION
  aws_default_region:
    file: wal-e/AWS_DEFAULT_REGION
  aws_secret_access_key:
    file: wal-e/AWS_SECRET_ACCESS_KEY
  wale_s3_prefix:
    file: wal-e/WALE_S3_PREFIX_S