version: '3.3'
services:

  haproxy:
    image: haproxy:alpine
    ports:
        - "5000:5000"
        - "5001:5001"
        - "8008:8008"
    configs: 
      - haproxy_cfg
    networks:
      - dbs
    command: haproxy -f /haproxy_cfg
  
  etcdnode1:
    image: quay.io/coreos/etcd:v3.1.2
    configs:
      - etcd_cfg
    networks: 
      - dbs
    command: /bin/sh /etcd_cfg

  dbnode1:
    image: seocahill/patroni:1.2.5
    secrets: 
      - patroni.yml
    env_file:
      - db-1.env
    networks:
      - dbs
    entrypoint: patroni
    command: /run/secrets/patroni.yml

  dbnode2:
    image: seocahill/patroni:1.2.5
    secrets: 
      - patroni.yml
    env_file:
      - db-2.env
    networks:
      - dbs
    entrypoint: patroni
    command: /run/secrets/patroni.yml
    
  dbnode3:
    image: seocahill/patroni:1.2.5
    secrets: 
      - patroni.yml
    env_file:
      - db-3.env
    networks:
      - dbs
    entrypoint: patroni
    command: /run/secrets/patroni.yml

networks:
  dbs:
    external: true

configs:
  haproxy_cfg:
    file: config/haproxy.cfg
  etcd_cfg:
    file: config/etcd.sh

secrets:
  patroni.yml:
    file: patroni.test.yml